Update CONTRIBUTING.md with pictures and instructions
CodenCommunity/Coden.github.io pull request #1
Opened 2021-07-30 07:24 UTC by Michelle-Lohwt

2021-08-01 09:27 UTC, LeeRenJie commented on .github/CONTRIBUTING.md
> +$ git clone https://github.com/<your-username>/Coden.github.io
Better to show this(from forked repo), easier to copy and paste. ![image](https://user-images.githubusercontent.com/67599130/127766069-fb4aae01-71e2-471a-bf92-da1c2e56db23.png)

2021-08-01 09:28 UTC, LeeRenJie commented on .github/CONTRIBUTING.md
> +$ cd repo_name
```suggestion
$ cd Coden.github,io
```

2021-08-01 09:31 UTC, LeeRenJie commented on .github/CONTRIBUTING.md
> +* Wait for the Issue to be assigned to you after which you can start working on it.
```suggestion
* Comment under the issue to work on it.
* Wait for an admin to assign the Issue to you before working on it. 
* Admin will assign to contributors based on first come first serve (FCFS) basis, 
* If the issue is not completed or without progress for a limited time, it will be open for other contributors to work on it.
```

2021-08-01 09:35 UTC, LeeRenJie commented on .github/CONTRIBUTING.md
> +![pull_request](https://github.com/Michelle-Lohwt/Coden.github.io/blob/branch1/assets/pic7_create_pull.png)
For this pic, the arrow would be better if pointed at the "compare & pull request"

2021-08-01 09:39 UTC, LeeRenJie requested changes
Rather than using blockquote, would be better if you use 
![image](https://user-images.githubusercontent.com/67599130/127766368-988a1a79-8fd0-40b8-9b6d-9a0ee40a9b57.png)

Example: 

```bash
#add files
$ git add .

#commit
$ git commit -m "message"
```

Can see the colour and know which should be copied.

2021-08-02 02:33 UTC, closed without merging

2021-08-02 02:56 UTC, Michelle-Lohwt reviewed
Please review the changes made:
- add/ modify images per request
- move images to assets/images
- add `bash` to codes